### ISSUE TITLE
Show avatars of unread messages on top bar.

### ISSUE THREAD

**Issue by RasmusRendal** [Benjadahl/UDPlus-Plus#16]
![untitled](https://cloud.githubusercontent.com/assets/19538856/19112402/e9daf8f2-8b04-11e6-9d6e-33b5ddacc034.png)
Mockup included

**Comment by Benjadahl** [comment]
Gr8 mockup m8

**Comment by RasmusRendal** [comment]
This is just infeasible. Not worth the effort
