### ISSUE TITLE
Abillity to make a custom theme from settings panel

### ISSUE THREAD

**Issue by mads256h** [Benjadahl/UDPlus-Plus#21]
The abillity to make a custom theme from hex values, from settings. I kinda dislike the current themes and i want to be able to make my own easly only from hex color.

**Comment by jbjjbjjbj** [comment]
Yeah i throught the same :-D  Good idea

**Comment by jbjjbjjbj** [comment]
I will try to make this in the customtheme branch

**Comment by Benjadahl** [comment]
Is this feature ready for beta release?

**Comment by jbjjbjjbj** [comment]
Jer dette er klart til beta@Benjadahl
