### ISSUE TITLE
Bug: Chrome not hiding finished assignments when pressing back button

### ISSUE THREAD

**Issue by mads256h** [Benjadahl/UDPlus-Plus#23]
Browser: Chrome

Going back from this page. [http://i.imgur.com/NHKZ2JE.png](http://i.imgur.com/NHKZ2JE.png)
[http://i.imgur.com/15APE1z.png](http://i.imgur.com/15APE1z.png)
It does not hide finished assignments: [http://i.imgur.com/X2loKtm.png](http://i.imgur.com/X2loKtm.png)

**Comment by Benjadahl** [comment]
This should be an easy fix, have to add a handler for the back button. However this is not high priority, since it is not very urgent.

**Comment by Benjadahl** [comment]
This bug has been fixed as of commit 1564074 (on branch development), it will be a part of the next update :)
