### ISSUE TITLE
Weird bar on uddata schedule

### ISSUE THREAD

**Issue by jbjjbjjbj** [Benjadahl/UDPlus-Plus#61]
Weird bar on 7 day calender in uddataplus schedule.

**Comment by jbjjbjjbj** [comment]
Problem does not exist in 2.0.0

**Comment by jbjjbjjbj** [comment]
Bug was introduced in commit 1a4afde

**Comment by jbjjbjjbj** [comment]
Bug was introduced in commit 1a4afde

**Comment by RasmusRendal** [comment]
Fixed in 3b8156e02a70ff50609192b7791654ce179e7b13
