### ISSUE TITLE
Grade average broken again

### ISSUE THREAD

**Issue by RasmusRendal** [Benjadahl/UDPlus-Plus#64]
We got new grades, and now grade average is broken yet again. Maybe this time, make it so that if there are no current grades, use the one from last period?

**Comment by agraven** [comment]
Would it be possible to make a more future-proof behavior that simply iterates through all columns with numbers in them and calculates their average, or would that be too complicated/messy? Or is the HTML too inflexible to deal with like that?

**Comment by RasmusRendal** [comment]
I think that's pretty much what it does right now. The difficult thing is also getting if the subject is A, B or C level, since that also has an effect on your grades.
But if you'd like to try and fix it, go right ahead, and don't feel afraid to ask for help!

**Comment by agraven** [comment]
I'm occupied with other things at present moment, but if I get the time, I'll look into parsing the class name for its level, and then iterating through the columns.

**Comment by RasmusRendal** [comment]
Well, there's already a pretty good regex for that, so no need.

**Comment by RasmusRendal** [comment]
Fixed grade average, and also added A-subject bonus, and a thing to display "startbonus".
