### ISSUE TITLE
Determine if lesson note is homework, by checkbox rather than filter

### ISSUE THREAD

**Issue by viktorstrate** [Benjadahl/UDPlus-Plus#66]
In settings you can set a filter for what notes are declared as homework, but there is a checkmark in the notes itself, why not use that?

![uddata popup](https://user-images.githubusercontent.com/4233458/29360480-65ba47c2-8283-11e7-94ff-7bfdb15451cf.png)

**Comment by RasmusRendal** [comment]
Sadly, the page only sends the request to find out if the lesson has homework after you click to check. While it's technically possible to figure out how that process works and send it ourselves, it's just too much work for any one of us existing developers to bother with. Of course, if you'd like to try your hand at it, we are very open to pull requests.
