### ISSUE TITLE
Access denied for to this service

### ISSUE THREAD

**Issue by RasmusRendal** [Benjadahl/UDPlus-Plus#72]
How about we just automatically press OK, because this seems to be another error message which means nothing.

**Comment by jbjjbjjbj** [comment]
Kinda fixed this in commit 2ecb9f8. It checks every second and if it finds the popup it will make a button close event. The problem with this method is that if UDDATA fixes the popup it will keep checking for nothing. This could be solved by adding a max amount of checks.

A better solution would be to listen to the 403 POST error, that occurs just before the popup. But after some research i could not find a way to do this.

**Comment by jbjjbjjbj** [comment]
Added the max amount in commit 852afce.

**Comment by jbjjbjjbj** [comment]
Im closing this issue because it was just fixed by uddata.
